### ISSUE TITLE
Cloudstack VMs are often killed by Scalr before they start

### ISSUE THREAD

**Issue by awheeler** [Scalr/scalr#41] opened 2014-10-24 13:45 UTC
I am using the latest Scalr Open Source (5.0), but this problem is not new.
When Scalr requests a new instance from Cloudstack, it often shows pending terminated almost immediately.
After much debugging, it turns out that when Cloudstack first creates a new VM, it's initial state is stopped, and Scalr treats stopped as a terminated state (should really be suspended if anything):
https://github.com/Scalr/scalr/blob/master/app/src/Scalr/Modules/Platforms/Cloudstack/Adapters/StatusAdapter.php#L37
As a result, the Poller.php cron-ng job kills it, thinking it's already terminated:
https://github.com/Scalr/scalr/blob/master/app/cron-ng/jobs/Poller.php#L445

I have patched both pieces of code to correct this, and found that **most** of this problem is addressed.  There is still a situation where CloudStack returns a status of 'not-found', but the CloudStack VM ends up in a running state anyway (though killed by Scalr), which happens at line 445 as well.

If you'd like, I can submit a patch.

**Comment by awheeler** [comment] 2015-02-23 21:35
Did the fix make it into 5.1, or 5.3, or?

**Comment by krallin** [comment] 2015-02-23 22:19
I'll let @DicsyDel handle that one as well!

**Comment by DicsyDel** [comment] 2015-02-24 00:01
This should be fixed in 5.3, at least we were not able to reproduce this in 5.3 branch after big refactoring of CloudPoller  cronjob. Feel free to re-open this ticket if after upgrading to 5.3 you'll continue to get same behavior.

Regards,
Igor

**Closed by DicsyDel** 2015-02-24 00:01 UTC

**Comment by awheeler** [comment] 2015-02-24 14:58
Fantastic news.  Do you have an ETA on 5.3 dropping?

**Comment by krallin** [comment] 2015-02-24 15:03
Hey Alex,

It should ship later this week. It's already in a branch of things repo,
the packages aren't ready yet is all.

Cheers,

**Comment by awheeler** [comment] 2015-02-24 15:11
Excellent!  I  did see the new branch.  I also see there is no 5.2, so the upgrade instructions are a little confusing on that front.  Would I just aggregate the 5.1->5.2, and 5.2->5.3 instructions?

**Comment by krallin** [comment] 2015-02-24 15:19
Hey Alex,

That's correct. Scalr 5.2 did exist, only it wasn't an OSS release : )

There will be packages (debs and RPMs) once we do publish 5.3.

Cheers,

**Comment by awheeler** [comment] 2015-02-25 15:55
Now that I am on 5.1, and lost my work-arounds, I am trying DicsyDel's comment from Dec 23, 2014, as I am experiencing the issue again.  Looking forward to 5.3 packages.
